import Head from "next/head";
import React, { ReactNode } from "react";


type LayoutProps = {
    children: ReactNode;
}

export const Layout = ({children}:LayoutProps) =>{ 
return (
    <div>

        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>

            <header>

            </header>
            <main>
                {children}
            </main>
            <footer>

            </footer> 

        </div>
    </div>
)
}